version: '3.8'

services:
  k2think-api:
    image: julienol/k2think2api:latest
    container_name: k2think-api
    ports:
      - "${HOST_PORT:-8001}:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped