version: '3.8'

services:
  k2think-api:
    image: julienol/k2think2api:latest
    container_name: k2think-api
    ports:
      - "${HOST_PORT:-8001}:8001"
    volumes:
      # 使用目录挂载而非文件挂载，避免文件锁定问题
      - ./data:/app/data
      # 或者使用命名卷（推荐用于生产环境）
      # - k2think_data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - PYTHONLEGACYWINDOWSSTDIO=0
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      # 更新配置文件路径指向data目录
      - TOKENS_FILE=/app/data/tokens.txt
      - ACCOUNTS_FILE=/app/data/accounts.txt
    restart: unless-stopped
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 可选：使用命名卷（推荐用于生产环境）
# volumes:
#   k2think_data:
#     driver: local